name: Deploy

on: push

jobs:
  deploy:
    env:
      SONATYPE_CREDENTIALS: ${{ secrets.SONATYPE_CREDENTIALS}}
      SIGNING_ARMORED_KEY: ${{ secrets.SIGNING_ARMORED_KEY}}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD}}
    if: github.repository_owner == 'meniga' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Deploy branch snapshot
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          ./gradlew \
          currentVersion \
          publishSnapshot
      - name: Deploy tagged release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          ./gradlew \
          currentVersion \
          publishRelease
